# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawRecord01',
            fields=[
                ('newsId', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('srcUrl', models.URLField()),
                ('title', models.CharField(max_length=500)),
                ('postTime', models.BigIntegerField()),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Result01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventLevel', models.IntegerField(default=0)),
                ('keywords', models.CharField(max_length=400)),
                ('name', models.CharField(max_length=200)),
                ('digest', models.TextField()),
                ('raw_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.RawRecord01')),
            ],
        ),
    ]
